[package]
name = "nerve"
version = "0.1.0"
authors = ["Josh Mcguigan"]
edition = "2018"

[dependencies]

[dev-dependencies]
test-utils = { path = "test-utils" }
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "mandel"
harness = false
